language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'

services:
    - mysql

before_script:
    - composer install
#    - mysql -e 'create database dsql_test;'

after_success:
    - echo $TRAVIS_PHP_VERSION
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then echo "Sending coverage report"; vendor/bin/test-reporter; fi
    - bash <(curl -s https://codecov.io/bash) -s build/logs

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.0" ]]; then NC="--no-coverage"; fi
    - ./vendor/phpunit/phpunit/phpunit $NC

cache:
  directories:
    - $HOME/.composer/cache

notifications:
    urls:
      - https://webhooks.gitter.im/e/b33a2db0c636f34bafa9

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

    email: false
